Update create-php-release.yml (#143)

diff --git a/.github/workflows/create-php-release.yml b/.github/workflows/create-php-release.yml
--- a/.github/workflows/create-php-release.yml
+++ b/.github/workflows/create-php-release.yml
@@ -47,15 +47,19 @@ jobs:
           git config --global url."https://${{ secrets.TOMLIKED_PAT }}@github.com/".insteadOf "https://github.com/"
           git remote add release-repo https://github.com/amzn/selling-partner-api-php-release.git
           
-      - name: Push to Target Repository with Debug
+      - name: Set Remote URL with Debug
         run: |
           set -x
           git remote set-url release-repo https://x-access-token:${{ secrets.TOMLIKED_PAT }}@github.com/amzn/selling-partner-api-php-release.git
-          git push release-repo $BRANCH_NAME --force
-
+      
       - name: Show Remote URL
         run: |
           echo "Remote URL is: $(git remote get-url release-repo)"
+      
+      - name: Push to Target Repository with Debug
+        run: |
+          set -x
+          git push release-repo $BRANCH_NAME --force || echo "Push failed, proceeding to remote URL check"
 
       - name: Create a Pull Request
         id: create_pr
